[book]
title = "docs"
authors = ["fadhil"]
description = "The book is a guide for the vs code extension to build smart contracts with the extension"
language = "en"
multilingual = false
src = "src"
text-direction= "ltr"