[book]
title = "docs"
authors = ["fadhil"]
description = "The book is a guide for the vs code extension to build smart contracts with the extension"
language = "en"
multilingual = false
src = "src"
text-direction= "ltr"

[output.html]
default-theme = "dark"
preferred-dark-theme = "navy"
additional-css = ["general.css"]
additional-js = ["custom.js"]
site-url = "https://buidlabz.github.io/ext-docs/"
git-repository-url = "https://github.com/buidlabz/ext-docs"
git-repository-icon = "fa-github"
